### ISSUE TITLE
error on index.html

### ISSUE THREAD

**Issue by 69sarthak69** [Manash111/Hostel_Management_System#1]
There is a error in index.html as the images is not loading
![Screenshot 2024-04-20 232822](https://github.com/Manash111/Hostel_Management_System/assets/127380488/15e520a7-73e8-4ddc-895f-d5c423070ae6)

**Comment by Manash111** [comment]
![image](https://github.com/Manash111/Hostel_Management_System/assets/76163583/3d8761a3-5abd-4601-9182-b0584dcc7660)
Fixed the error and updated the code.
