### ISSUE TITLE
error on form submission

### ISSUE THREAD

**Issue by Manash111** [Manash111/Hostel_Management_System#2]
When users submit the form without including the '@' symbol in the email field, the form still submits successfully, despite the email being incomplete or invalid.

**Comment by 69sarthak69** [comment]
Implemented validation checks on the email field to ensure that it contains the '@' symbol before allowing the form submission to proceed. Displaying  an error message prompting users to correct the email format if it is incomplete or invalid.
![image](https://github.com/Manash111/Hostel_Management_System/assets/127380488/c80b65ce-264e-447a-8f95-e32d235707be)
